### ISSUE TITLE
Add a Save Button and Dialog for the Template

### ISSUE THREAD

**Issue by tmarrs** [Rowno/architect#8]
Could you add a Save button and dialog for the Template?

**Comment by Rowno** [comment]
Not sure it's necessary because I find copy+paste to be faster and more convenient, since you don't have to navigate to the correct folder or move the downloaded file. But I guess it could easily be done by [encoding the template into a link data URI](https://stackoverflow.com/questions/3665115/create-a-file-in-memory-for-user-to-download-not-through-server).

**Comment by tmarrs** [comment]
You're right of course. The copy+paste works well. Anyway, thanks for developing such a great tool - I use it every day at work.

**Comment by Rowno** [comment]
Thanks :blush:
